# Generated by Django 5.0.6 on 2024-12-26 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_alter_order_voucher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='voucher',
        ),
    ]
