# Generated by Django 5.0.6 on 2024-12-27 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_remove_order_voucher'),
        ('Voucher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='oucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Voucher.voucher'),
        ),
    ]
