# Generated by Django 5.0.6 on 2024-12-27 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_order_oucher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='oucher',
            new_name='voucher',
        ),
    ]
