# Generated by Django 5.0.6 on 2024-12-31 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_rename_oucher_order_voucher'),
        ('vnpay_python', '0002_payment_delete_paymentform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='purchase_date',
        ),
        migrations.AddField(
            model_name='order',
            name='pay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vnpay_python.payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_order_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
