# Generated by Django 5.0.6 on 2024-12-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0007_remove_order_purchase_date_order_pay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='purchase_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
