# Generated by Django 5.0.6 on 2024-12-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=250)),
                ('order_type', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('order_desc', models.CharField(max_length=100)),
                ('bank_code', models.CharField(blank=True, max_length=20, null=True)),
                ('language', models.CharField(choices=[('vn', 'Tiếng Việt'), ('en', 'English')], default='vn', max_length=2)),
            ],
        ),
    ]
