# Generated by Django 5.0.6 on 2024-12-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vnpay_python', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order_desc', models.TextField(blank=True)),
                ('transaction_no', models.CharField(max_length=100, unique=True)),
                ('response_code', models.CharField(max_length=10)),
                ('pay_date', models.CharField(max_length=14)),
                ('bank_code', models.CharField(blank=True, max_length=20)),
                ('card_type', models.CharField(blank=True, max_length=50)),
                ('tmn_code', models.CharField(blank=True, max_length=50)),
                ('checksum_valid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PaymentForm',
        ),
    ]
