# Generated by Django 5.0.6 on 2024-12-27 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Voucher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucheruser',
            name='amount_paid',
        ),
    ]
