# Generated by Django 5.0.6 on 2024-12-26 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0004_sale_remove_good_color_good_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='sales',
        ),
    ]
