# Generated by Django 5.0.6 on 2024-12-18 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_address_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='addressct',
        ),
    ]
