# Generated by Django 5.0.6 on 2024-12-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_rename_address_address_addressct'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
